### ISSUE TITLE
The animation function is causing an continous exception

### ISSUE THREAD

**Issue by moorepants** [moorepants/resonance#39]
```
ERROR:tornado.application:Exception in callback <bound method TimerBase._on_timer of <matplotlib.backends.backend_webagg_core.TimerTornado object at 0x7f2b5f1da748>>
Traceback (most recent call last):
  File "/home/moorepants/miniconda3/envs/resonance/lib/python3.6/site-packages/tornado/ioloop.py", line 1026, in _run
    return self.callback()
  File "/home/moorepants/miniconda3/envs/resonance/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1319, in _on_timer
    ret = func(*args, **kwargs)
  File "/home/moorepants/miniconda3/envs/resonance/lib/python3.6/site-packages/matplotlib/animation.py", line 1293, in _step
    self._init_draw()
  File "/home/moorepants/miniconda3/envs/resonance/lib/python3.6/site-packages/matplotlib/animation.py", line 1540, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
StopIteration
```

I have to CTRL-C to kill it from the terminal.

**Comment by moorepants** [comment]
@ixjlyons Do you have any thoughts on this one? We might have everyone in the class spooling these up, which draw significant cpu.

**Comment by moorepants** [comment]
Ok, but this keeps running even if you close the figure. Doesn't stop till notebook is closed.

**Comment by ixjlyons** [comment]
For the record, if they leave a notebook running with an animation that continuously wastes cycles like this, I can SIGTERM the individual IPython kernel process. Their connection to the hub is fine, and it only affects the specific notebook. It pops up a message "The kernel appears to have died. It will restart automatically." and if they press ok it just shows the notebook, having done what it says. Unsaved changes are left intact.

**Comment by moorepants** [comment]
Ok, it seems that the matplotlib animations loop by default, but at the end of the first pass through, this "StopIteration" error is occurring and preventing the loop. If you set `repeat=False` the error doesn't occur. So we could set that by default internally to the System and things would be fine. Figuring out why the looping is failing is still an issue. It has something to do with the way we've setup the animation that is different than a standard script I suppose.

**Comment by moorepants** [comment]
This seems to have to do with the animation not being able to repeat. You can have it throw traceback in the terminal:

```
(resonance-dev) moorepants@garuda:resonance(ani-interval)$ ipython --pdb
Python 3.6.3 | packaged by conda-forge | (default, Oct  5 2017, 14:07:33) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from resonance.linear_systems import SimpleQuarterCarSystem

In [2]: sys = SimpleQuarterCarSystem()

In [3]: traj = sys.sinusoidal_base_displacing_response(0.01, 7, 1, sample_rate=60)

In [4]: sys.animate_configuration()
Out[4]: <matplotlib.animation.FuncAnimation at 0x7f5b1801cc88>

In [5]: import matplotlib.pyplot as plt

In [6]: plt.show()
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
~/miniconda3/envs/resonance-dev/lib/python3.6/site-packages/matplotlib/backend_bases.py in _on_timer(self)
   1380         '''
   1381         for func, args, kwargs in self.callbacks:
-> 1382             ret = func(*args, **kwargs)
   1383             # docstring above explains why we use `if ret == False` here,
   1384             # instead of `if not ret`.

~/miniconda3/envs/resonance-dev/lib/python3.6/site-packages/matplotlib/animation.py in _step(self, *args)
   1542         still_going = Animation._step(self, *args)
   1543         if not still_going and self.repeat:
-> 1544             self._init_draw()
   1545             self.frame_seq = self.new_frame_seq()
   1546             if self._repeat_delay:

~/miniconda3/envs/resonance-dev/lib/python3.6/site-packages/matplotlib/animation.py in _init_draw(self)
   1790         # artists.
   1791         if self._init_func is None:
-> 1792             self._draw_frame(next(self.new_frame_seq()))
   1793 
   1794         else:

StopIteration: 
> /home/moorepants/miniconda3/envs/resonance-dev/lib/python3.6/site-packages/matplotlib/animation.py(1792)_init_draw()
   1790         # artists.
   1791         if self._init_func is None:
-> 1792             self._draw_frame(next(self.new_frame_seq()))
   1793 
   1794         else:
```

**Comment by moorepants** [comment]
Related to this save_count issue?: https://github.com/matplotlib/matplotlib/issues/8278

**Comment by moorepants** [comment]
Also this: https://stackoverflow.com/questions/20694016/matplotlib-animation-funcanimation-frames-argument

**Comment by moorepants** [comment]
Note that if I don't use a generator convert the generator to a list, everything works fine.
